// <auto-generated />
using System;
using DiarioDeBordo.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiarioDeBordo.Persistencia.Migrations
{
    [DbContext(typeof(DiarioDeBordoDbContext))]
    partial class DiarioDeBordoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("idx_categorias_usuario_nome_unique");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classificacao");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formato");

                    b.Property<bool>("IsFilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_filho");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("nota");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("papel");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subtipo");

                    b.Property<string>("TipoColetaneaValor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_coletanea");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo");

                    b.Property<int?>("TotalEsperadoSessoes")
                        .HasColumnType("integer")
                        .HasColumnName("total_esperado_sessoes");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_conteudos_usuario_id");

                    b.HasIndex("UsuarioId", "CriadoEm")
                        .HasDatabaseName("idx_conteudos_usuario_criado_em");

                    b.HasIndex("UsuarioId", "IsFilho")
                        .HasDatabaseName("idx_conteudos_usuario_is_filho");

                    b.ToTable("conteudos", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.ConteudoCategoria", b =>
                {
                    b.Property<Guid>("ConteudoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conteudo_id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTimeOffset>("AssociadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("associada_em");

                    b.HasKey("ConteudoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("conteudo_categorias", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Relacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConteudoDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conteudo_destino_id");

                    b.Property<Guid>("ConteudoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("conteudo_origem_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("IsInversa")
                        .HasColumnType("boolean")
                        .HasColumnName("is_inversa");

                    b.Property<Guid?>("ParId")
                        .HasColumnType("uuid")
                        .HasColumnName("par_id");

                    b.Property<Guid>("TipoRelacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_relacao_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ConteudoDestinoId");

                    b.HasIndex("ParId")
                        .HasDatabaseName("idx_relacoes_par_id");

                    b.HasIndex("TipoRelacaoId");

                    b.HasIndex("ConteudoOrigemId", "UsuarioId")
                        .HasDatabaseName("idx_relacoes_origem_usuario");

                    b.HasIndex("ConteudoOrigemId", "ConteudoDestinoId", "TipoRelacaoId")
                        .IsUnique()
                        .HasDatabaseName("idx_relacoes_origem_destino_tipo_unique");

                    b.ToTable("relacoes", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.TipoRelacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sistema");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeInverso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_inverso");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("idx_tipo_relacoes_usuario_nome_unique");

                    b.ToTable("tipo_relacoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsSistema = true,
                            Nome = "Sequência",
                            NomeInverso = "Continuação de",
                            NomeNormalizado = "sequência",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsSistema = true,
                            Nome = "Derivado de",
                            NomeInverso = "Derivou",
                            NomeNormalizado = "derivado de",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsSistema = true,
                            Nome = "Referenciado em",
                            NomeInverso = "Referencia",
                            NomeNormalizado = "referenciado em",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsSistema = true,
                            Nome = "Adaptação de",
                            NomeInverso = "Adaptado em",
                            NomeNormalizado = "adaptação de",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsSistema = true,
                            Nome = "Alternativa a",
                            NomeInverso = "Alternativa a",
                            NomeNormalizado = "alternativa a",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsSistema = true,
                            Nome = "Do mesmo tipo que",
                            NomeInverso = "Do mesmo tipo que",
                            NomeNormalizado = "do mesmo tipo que",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsSistema = true,
                            Nome = "Complemento de",
                            NomeInverso = "Complementado por",
                            NomeNormalizado = "complemento de",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsSistema = true,
                            Nome = "Pré-requisito para",
                            NomeInverso = "Requer",
                            NomeNormalizado = "pré-requisito para",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsSistema = true,
                            Nome = "Contém",
                            NomeInverso = "Parte de",
                            NomeNormalizado = "contém",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Conteudo", b =>
                {
                    b.OwnsMany("DiarioDeBordo.Core.Entidades.Fonte", "Fontes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid")
                                .HasColumnName("conteudo_id");

                            b1.Property<string>("Plataforma")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("plataforma");

                            b1.Property<int>("Prioridade")
                                .HasColumnType("integer")
                                .HasColumnName("prioridade");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tipo");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("valor");

                            b1.HasKey("Id");

                            b1.HasIndex("ConteudoId", "Prioridade")
                                .IsUnique()
                                .HasDatabaseName("idx_fontes_conteudo_prioridade_unique");

                            b1.ToTable("fontes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.OwnsMany("DiarioDeBordo.Core.Entidades.ImagemConteudo", "Imagens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Caminho")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("caminho");

                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid")
                                .HasColumnName("conteudo_id");

                            b1.Property<string>("OrigemTipo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origem_tipo");

                            b1.Property<bool>("Principal")
                                .HasColumnType("boolean")
                                .HasColumnName("principal");

                            b1.HasKey("Id");

                            b1.HasIndex("ConteudoId");

                            b1.ToTable("imagens_conteudo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.OwnsOne("DiarioDeBordo.Core.Entidades.Progresso", "Progresso", b1 =>
                        {
                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("progresso_estado");

                            b1.Property<string>("NotaManual")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("progresso_nota_manual");

                            b1.Property<string>("PosicaoAtual")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("progresso_posicao_atual");

                            b1.HasKey("ConteudoId");

                            b1.ToTable("conteudos");

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.Navigation("Fontes");

                    b.Navigation("Imagens");

                    b.Navigation("Progresso")
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.ConteudoCategoria", b =>
                {
                    b.HasOne("DiarioDeBordo.Core.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioDeBordo.Core.Entidades.Conteudo", null)
                        .WithMany()
                        .HasForeignKey("ConteudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Relacao", b =>
                {
                    b.HasOne("DiarioDeBordo.Core.Entidades.Conteudo", null)
                        .WithMany()
                        .HasForeignKey("ConteudoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioDeBordo.Core.Entidades.Conteudo", null)
                        .WithMany()
                        .HasForeignKey("ConteudoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiarioDeBordo.Core.Entidades.TipoRelacao", null)
                        .WithMany()
                        .HasForeignKey("TipoRelacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
