// <auto-generated />
using System;
using DiarioDeBordo.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiarioDeBordo.Persistencia.Migrations
{
    [DbContext(typeof(DiarioDeBordoDbContext))]
    partial class DiarioDeBordoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("idx_categorias_usuario_nome_unique");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formato");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("nota");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("papel");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subtipo");

                    b.Property<string>("TipoColetaneaValor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_coletanea");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_conteudos_usuario_id");

                    b.HasIndex("UsuarioId", "CriadoEm")
                        .HasDatabaseName("idx_conteudos_usuario_criado_em");

                    b.ToTable("conteudos", (string)null);
                });

            modelBuilder.Entity("DiarioDeBordo.Core.Entidades.Conteudo", b =>
                {
                    b.OwnsMany("DiarioDeBordo.Core.Entidades.Fonte", "Fontes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid")
                                .HasColumnName("conteudo_id");

                            b1.Property<string>("Plataforma")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("plataforma");

                            b1.Property<int>("Prioridade")
                                .HasColumnType("integer")
                                .HasColumnName("prioridade");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tipo");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("valor");

                            b1.HasKey("Id");

                            b1.HasIndex("ConteudoId", "Prioridade")
                                .IsUnique()
                                .HasDatabaseName("idx_fontes_conteudo_prioridade_unique");

                            b1.ToTable("fontes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.OwnsMany("DiarioDeBordo.Core.Entidades.ImagemConteudo", "Imagens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Caminho")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("caminho");

                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid")
                                .HasColumnName("conteudo_id");

                            b1.Property<string>("OrigemTipo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("origem_tipo");

                            b1.Property<bool>("Principal")
                                .HasColumnType("boolean")
                                .HasColumnName("principal");

                            b1.HasKey("Id");

                            b1.HasIndex("ConteudoId");

                            b1.ToTable("imagens_conteudo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.OwnsOne("DiarioDeBordo.Core.Entidades.Progresso", "Progresso", b1 =>
                        {
                            b1.Property<Guid>("ConteudoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("progresso_estado");

                            b1.Property<string>("NotaManual")
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)")
                                .HasColumnName("progresso_nota_manual");

                            b1.Property<string>("PosicaoAtual")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("progresso_posicao_atual");

                            b1.HasKey("ConteudoId");

                            b1.ToTable("conteudos");

                            b1.WithOwner()
                                .HasForeignKey("ConteudoId");
                        });

                    b.Navigation("Fontes");

                    b.Navigation("Imagens");

                    b.Navigation("Progresso")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
