// <auto-generated />
using System;
using DiarioDeBordo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiarioDeBordo.Persistence.Migrations
{
    [DbContext(typeof(DiarioDeBordoDbContext))]
    partial class DiarioDeBordoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiarioDeBordo.Domain.Obras.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUltimaAtualizacaoPosicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiasAteProximaParte")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrdemPreferencia")
                        .HasColumnType("integer");

                    b.Property<int?>("PartesJaPublicadas")
                        .HasColumnType("integer");

                    b.Property<int>("PosicaoAtual")
                        .HasColumnType("integer");

                    b.Property<string>("ProximaInfoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Obras", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
